[2024-06-20 03:07:00,829] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T03:06:36.840405+00:00 [queued]>
[2024-06-20 03:07:00,844] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T03:06:36.840405+00:00 [queued]>
[2024-06-20 03:07:00,845] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-20 03:07:00,845] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-20 03:07:00,846] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-20 03:07:00,866] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_mail> on 2024-06-19 03:06:36.840405+00:00
[2024-06-20 03:07:00,874] {standard_task_runner.py:52} INFO - Started process 4383 to run task
[2024-06-20 03:07:00,878] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'desafio3_pipeline', 'send_mail', 'scheduled__2024-06-19T03:06:36.840405+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpc2vock0p', '--error-file', '/tmp/tmpcvnx7lxi']
[2024-06-20 03:07:00,880] {standard_task_runner.py:80} INFO - Job 30: Subtask send_mail
[2024-06-20 03:07:00,994] {task_command.py:371} INFO - Running <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T03:06:36.840405+00:00 [running]> on host 3f4d47b0555b
[2024-06-20 03:07:01,104] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=desafio3_pipeline
AIRFLOW_CTX_TASK_ID=send_mail
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T03:06:36.840405+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-19T03:06:36.840405+00:00
[2024-06-20 03:07:02,904] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-1f855e56535sm124963465ad.55 - gsmtp')
[2024-06-20 03:07:02,905] {logging_mixin.py:115} INFO - El email no se pudo enviar.
[2024-06-20 03:07:02,905] {python.py:173} INFO - Done. Returned value was: None
[2024-06-20 03:07:02,934] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=desafio3_pipeline, task_id=send_mail, execution_date=20240619T030636, start_date=20240620T030700, end_date=20240620T030702
[2024-06-20 03:07:02,979] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-06-20 03:07:03,028] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
