[2024-06-20 01:56:02,222] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T01:56:00.928674+00:00 [queued]>
[2024-06-20 01:56:02,244] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T01:56:00.928674+00:00 [queued]>
[2024-06-20 01:56:02,245] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-20 01:56:02,246] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-20 01:56:02,246] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-20 01:56:02,282] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_mail> on 2024-06-19 01:56:00.928674+00:00
[2024-06-20 01:56:02,291] {standard_task_runner.py:52} INFO - Started process 1988 to run task
[2024-06-20 01:56:02,295] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'desafio3_pipeline', 'send_mail', 'scheduled__2024-06-19T01:56:00.928674+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpx1eqkovu', '--error-file', '/tmp/tmp1xh0j5m7']
[2024-06-20 01:56:02,298] {standard_task_runner.py:80} INFO - Job 21: Subtask send_mail
[2024-06-20 01:56:02,436] {task_command.py:371} INFO - Running <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T01:56:00.928674+00:00 [running]> on host 3f4d47b0555b
[2024-06-20 01:56:02,829] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=desafio3_pipeline
AIRFLOW_CTX_TASK_ID=send_mail
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T01:56:00.928674+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-19T01:56:00.928674+00:00
[2024-06-20 01:56:05,289] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-1f855f40947sm123957355ad.276 - gsmtp')
[2024-06-20 01:56:05,289] {logging_mixin.py:115} INFO - El email no se pudo enviar.
[2024-06-20 01:56:05,290] {python.py:173} INFO - Done. Returned value was: None
[2024-06-20 01:56:05,314] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=desafio3_pipeline, task_id=send_mail, execution_date=20240619T015600, start_date=20240620T015602, end_date=20240620T015605
[2024-06-20 01:56:05,372] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-06-20 01:56:05,433] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
