[2024-06-20 02:26:30,229] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T02:26:17.654416+00:00 [queued]>
[2024-06-20 02:26:30,251] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T02:26:17.654416+00:00 [queued]>
[2024-06-20 02:26:30,252] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-20 02:26:30,252] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-20 02:26:30,252] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-20 02:26:30,281] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): send_mail> on 2024-06-19 02:26:17.654416+00:00
[2024-06-20 02:26:30,291] {standard_task_runner.py:52} INFO - Started process 3015 to run task
[2024-06-20 02:26:30,296] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'desafio3_pipeline', 'send_mail', 'scheduled__2024-06-19T02:26:17.654416+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmpzbpevz4q', '--error-file', '/tmp/tmpfaxspf7r']
[2024-06-20 02:26:30,298] {standard_task_runner.py:80} INFO - Job 24: Subtask send_mail
[2024-06-20 02:26:30,408] {task_command.py:371} INFO - Running <TaskInstance: desafio3_pipeline.send_mail scheduled__2024-06-19T02:26:17.654416+00:00 [running]> on host 3f4d47b0555b
[2024-06-20 02:26:30,586] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=desafio3_pipeline
AIRFLOW_CTX_TASK_ID=send_mail
AIRFLOW_CTX_EXECUTION_DATE=2024-06-19T02:26:17.654416+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-19T02:26:17.654416+00:00
[2024-06-20 02:26:32,540] {logging_mixin.py:115} INFO - (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials d9443c01a7336-1f855ee80a1sm124966205ad.150 - gsmtp')
[2024-06-20 02:26:32,541] {logging_mixin.py:115} INFO - El email no se pudo enviar.
[2024-06-20 02:26:32,542] {python.py:173} INFO - Done. Returned value was: None
[2024-06-20 02:26:32,562] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=desafio3_pipeline, task_id=send_mail, execution_date=20240619T022617, start_date=20240620T022630, end_date=20240620T022632
[2024-06-20 02:26:32,598] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-06-20 02:26:32,655] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
