[2024-06-03 14:55:36,384] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.etl_data scheduled__2024-06-02T14:55:34.594598+00:00 [queued]>
[2024-06-03 14:55:36,408] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: desafio3_pipeline.etl_data scheduled__2024-06-02T14:55:34.594598+00:00 [queued]>
[2024-06-03 14:55:36,409] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2024-06-03 14:55:36,410] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2024-06-03 14:55:36,411] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2024-06-03 14:55:36,446] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): etl_data> on 2024-06-02 14:55:34.594598+00:00
[2024-06-03 14:55:36,459] {standard_task_runner.py:52} INFO - Started process 205 to run task
[2024-06-03 14:55:36,462] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'desafio3_pipeline', 'etl_data', 'scheduled__2024-06-02T14:55:34.594598+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/weather_dags.py', '--cfg-path', '/tmp/tmphc74kfz_', '--error-file', '/tmp/tmp33shmx0n']
[2024-06-03 14:55:36,464] {standard_task_runner.py:80} INFO - Job 10: Subtask etl_data
[2024-06-03 14:55:36,571] {task_command.py:371} INFO - Running <TaskInstance: desafio3_pipeline.etl_data scheduled__2024-06-02T14:55:34.594598+00:00 [running]> on host 3dead8e38494
[2024-06-03 14:55:36,690] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=desafio3_pipeline
AIRFLOW_CTX_TASK_ID=etl_data
AIRFLOW_CTX_EXECUTION_DATE=2024-06-02T14:55:34.594598+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-06-02T14:55:34.594598+00:00
[2024-06-03 14:55:41,322] {logging_mixin.py:115} INFO - Conectado a Redshift con éxito!
[2024-06-03 14:55:46,872] {python.py:173} INFO - Done. Returned value was:            city weather_description  ...              sunset        day
0  Buenos Aires           clear sky  ... 2024-06-03 17:50:23 2024-06-03
1       Mendoza       broken clouds  ... 2024-06-03 18:36:20 2024-06-03
2    Corrientes    scattered clouds  ... 2024-06-03 18:08:23 2024-06-03
3         Salta     overcast clouds  ... 2024-06-03 18:40:13 2024-06-03
4       Córdoba           clear sky  ... 2024-06-03 18:21:11 2024-06-03

[5 rows x 11 columns]
[2024-06-03 14:55:46,903] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2024-06-03 14:55:46,905] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2024-06-03 14:55:46,918] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=desafio3_pipeline, task_id=etl_data, execution_date=20240602T145534, start_date=20240603T145536, end_date=20240603T145546
[2024-06-03 14:55:46,939] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task etl_data (Object of type DataFrame is not JSON serializable; 205)
[2024-06-03 14:55:46,967] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-06-03 14:55:47,012] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
